# Generated by Django 3.2 on 2021-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_detail', models.CharField(max_length=255)),
                ('book_price', models.IntegerField(max_length=255)),
                ('book_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
