# Generated by Django 3.2 on 2021-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='book_category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_details',
            name='book_isbn',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_details',
            name='book_publish',
            field=models.IntegerField(default='2015', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_details',
            name='book_type',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
    ]
